// <auto-generated />
namespace Final_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class truckdrivers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(truckdrivers));
        
        string IMigrationMetadata.Id
        {
            get { return "202306122105519_truck-drivers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
